### ISSUE TITLE
GPLv2 License

### ISSUE THREAD

**Issue by ToniTornado** [SphericalKat/dart-fuzzywuzzy#3]
Can somebody explain to me what this license means for usage in my proprietary commercial Flutter project? I known there exists a "library exception" in the GPLv2. Does it apply to this package when I use it in my project? Unfortunately it is not possible for me to release the source code of the app where I plan to use this package.

Thank you!

**Comment by SphericalKat** [comment]
Hi, thanks for asking what's been bothering me for a long time honestly. 

This GPLv2 doesn't contain any of the "linking" exception clauses, and thus you'd have to provide sources for your __entire application__ on request if you ended up using this library. 

I would've preferred not to use a GPL license for this project and instead use something permissive like MIT or Apache for the widest compatibility; however the original authors of fuzzywuzzy licensed their library under the GPLv2, and I have to honour that license since this is technically a "derivative work". 

However fear not! Me and a friend are currently working on a "clean room" reimplementation that will be licensed under a permissive license and provide the same functionality.

If you have more questions, feel free to reach out. 

Cheers!
